CREATE TABLE T_PERSONNE_PRS 
(PRS_NOM    CHAR(16) NOT NULL, 
 PRS_VILLE  CHAR(16), 
 PRS_NOMBRE INTEGER); 

INSERT INTO T_PERSONNE_PRS VALUES ('MARTIN', 'PARIS', 3);
INSERT INTO T_PERSONNE_PRS VALUES ('DUPOND', 'STRASBOURG', 2);
