DROP TABLE IF EXISTS T_PROSPECT_PSP;
CREATE TABLE T_PROSPECT_PSP 
(PSP_NOM VARCHAR(16)); 

INSERT INTO T_PROSPECT_PSP VALUES ('ARMAND');
INSERT INTO T_PROSPECT_PSP VALUES ('DUPONT');
INSERT INTO T_PROSPECT_PSP VALUES ('BAILLE');
INSERT INTO T_PROSPECT_PSP VALUES ('GAUTIER');
INSERT INTO T_PROSPECT_PSP VALUES ('MARTIN');
INSERT INTO T_PROSPECT_PSP VALUES ('CLAUDE');
INSERT INTO T_PROSPECT_PSP VALUES ('DUPONT'); 
