CREATE TABLE TBL1  
(TBL_ID INTEGER); 

CREATE TABLE TBL2  
(TBL_ID INTEGER); 

CREATE TABLE TBL3  
(TBL_ID INTEGER); 

INSERT INTO TBL1 VALUES (1);
INSERT INTO TBL1 VALUES (3);
INSERT INTO TBL1 VALUES (5);
INSERT INTO TBL1 VALUES (7);
INSERT INTO TBL1 VALUES (9); 

INSERT INTO TBL2 VALUES (2);
INSERT INTO TBL2 VALUES (4);
INSERT INTO TBL2 VALUES (6);
INSERT INTO TBL2 VALUES (8); 

INSERT INTO TBL3 VALUES (1);
INSERT INTO TBL3 VALUES (2);
INSERT INTO TBL3 VALUES (3);
INSERT INTO TBL3 VALUES (5);
INSERT INTO TBL3 VALUES (7); 
